spring:
  config:
    activate:
      on-profile: security

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET} # 발급 받은 Client Secret
            scope: email

          naver:
            client-id: ${NAVER_CLIENT_ID} # 발급 받은 Client ID
            client-secret: ${NAVER_CLIENT_SECRET} # 발급 받은 Client Secret
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정
