spring:
  application:
    name: carekids
  profiles:
    group:
      dev: email, security, dev
      oper: email, security, oper
    active: oper

  sql:
    init:
      mode: always
      encoding: utf-8

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: ${SECRET_KEY}

file:
  upload-path: "C:\\uploads"