INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (1, '공지사항 제목1', '공지사항 내용1', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (2, '공지사항 제목2', '공지사항 내용2', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (3, '공지사항 제목3', '공지사항 내용3', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (4, '공지사항 제목4', '공지사항 내용4', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (5, '공지사항 제목5', '공지사항 내용5', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (6, '공지사항 제목6', '공지사항 내용6', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (7, '공지사항 제목7', '공지사항 내용7', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (8, '공지사항 제목8', '공지사항 내용8', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (9, '공지사항 제목9', '공지사항 내용9', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (10, '공지사항 제목10', '공지사항 내용10', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (11, '공지사항 제목11', '공지사항 내용11', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (12, '공지사항 제목12', '공지사항 내용12', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (13, '공지사항 제목13', '공지사항 내용13', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (14, '공지사항 제목14', '공지사항 내용14', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (15, '공지사항 제목15', '공지사항 내용15', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (16, '공지사항 제목16', '공지사항 내용16', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (17, '공지사항 제목17', '공지사항 내용17', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (18, '공지사항 제목18', '공지사항 내용18', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (19, '공지사항 제목19', '공지사항 내용19', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (20, '공지사항 제목20', '공지사항 내용20', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (21, '공지사항 제목21', '공지사항 내용21', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (22, '공지사항 제목22', '공지사항 내용22', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (23, '공지사항 제목23', '공지사항 내용23', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (24, '공지사항 제목24', '공지사항 내용24', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (25, '공지사항 제목25', '공지사항 내용25', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (26, '공지사항 제목26', '공지사항 내용26', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (27, '공지사항 제목27', '공지사항 내용27', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (28, '공지사항 제목28', '공지사항 내용28', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (29, '공지사항 제목29', '공지사항 내용29', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (30, '공지사항 제목30', '공지사항 내용30', now(), now(), FALSE);


INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (1, 'title1', 'test1', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (3, 'title3', 'test3', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (2, 'title2', 'test2', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (4, 'title4', 'test4', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (5, 'title5', 'test5', now(), now(), FALSE);


INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (1, 'title1', 'test1', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (2, 'title2', 'test2', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (3, 'title3', 'test3', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (4, 'title4', 'test4', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (5, 'title5', 'test5', now(), now(), FALSE);

INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (1, '0 ~ 3');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (2, '3 ~ 5');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (3, '6 ~ 7');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (4, '8 ~ 10');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (5, '10 ~ 13');

INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (1, 'region 1');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (2, 'region 2');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (3, 'region 3');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (4, 'region 4');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (5, 'region 5');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (6, 'region 6');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (7, 'region 7');
