INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (2, 'title2', 'test2', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (1, 'title1', 'test1', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (3, 'title3', 'test3', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (4, 'title4', 'test4', now(), now(), FALSE);
INSERT INTO NOTICE (NOTICE_ID, NOTICE_TITLE, NOTICE_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (5, 'title5', 'test5', now(), now(), FALSE);

INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (1, 'title1', 'test1', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (3, 'title3', 'test3', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (2, 'title2', 'test2', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (4, 'title4', 'test4', now(), now(), FALSE);
INSERT INTO KIDS_POLICY (KIDS_POLICY_ID , KIDS_POLICY_TITLE , KIDS_POLICY_TEXT , CREATED_AT , UPDATED_AT, DELETED) VALUES (5, 'title5', 'test5', now(), now(), FALSE);

INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (1, 'title1', 'test1', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (2, 'title2', 'test2', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (3, 'title3', 'test3', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (4, 'title4', 'test4', now(), now(), FALSE);
INSERT INTO PLAY_INFO (PLAY_INFO_ID, PLAY_INFO_TITLE, PLAY_INFO_TEXT, CREATED_AT, UPDATED_AT, DELETED) VALUES (5, 'title5', 'test5', now(), now(), FALSE);

INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (1, '0 ~ 3');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (2, '3 ~ 5');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (3, '6 ~ 7');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (4, '8 ~ 10');
INSERT INTO AGE_Tag (AGE_TAG_ID, AGE_TAG_NAME) VALUES (5, '10 ~ 13');

INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (1, 'region 1');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (2, 'region 2');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (3, 'region 3');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (4, 'region 4');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (5, 'region 5');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (6, 'region 6');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (7, 'region 7');